### ISSUE TITLE
Legal review of site

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/NSF-wireless-innovation-challenge#11]

**Comment by hannahkane** [comment]
Need to answer question about whether we're using standard T&C and Privacy Policy, and whether we need to update either.

cc @mehan @anmechung

**Comment by mehan** [comment]
I have put out an ask to Abigail and she is reviewing--will report back in this issue.

**Comment by hannahkane** [comment]
Complete, though Abigail will likely want to look at the event pages once they're ready.
