### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/NSF-wireless-innovation-challenge#12]
As per legal department, the links in the footer should point to:
- Legal: https://www.mozilla.org/en-US/about/legal/terms/mozilla/
- Privacy: https://www.mozilla.org/en-US/privacy/websites/
- Cookies: https://www.mozilla.org/en-US/privacy/websites/#cookies
- Challenge Rules: to be created on whatever domain we use for the challenge website

**Comment by hannahkane** [comment]
cc @mehan

**Comment by mehan** [comment]
Yep, looks good. 👍

**Comment by kristinashu** [comment]
Updating this to cover all footer links:

- Forum: https://forum.learning.mozilla.org/c/nsf-wins
- Legal: https://www.mozilla.org/en-US/about/legal/terms/mozilla/
- Privacy: https://www.mozilla.org/en-US/privacy/websites/
- Cookies: https://www.mozilla.org/en-US/privacy/websites/#cookies
- Challenge Rules: to be created on whatever domain we use for the challenge website (ideally, wirelesschallenge.mozilla.org/rules

**Comment by kristinashu** [comment]
Opened implementation ticket - UI: Footer #21
