### ISSUE TITLE
Design site

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#13]
Once initial copy and wireframes https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/1 are done, we can design the site using:
- new moco branding
- images from https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/7

**Comment by kristinashu** [comment]
Wireframes are done: https://redpen.io/p/cx1e480fd9bb50a788

I will be designing the site based on the new branding and https://internethealthreport.org/v01/

**Comment by kristinashu** [comment]
I've incorporated the new branding into the site: https://redpen.io/p/cx1e480fd9bb50a788

cc @hannahkane @mehan

**Comment by kristinashu** [comment]
Design is done! I made a few minor updates based on our meeting with the moco design but they're very minimal. 

Opened up a few tickets for dev to implement designs https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues

**Comment by hannahkane** [comment]
Thank you, @kristinashu. Really nice work on this!

**Comment by mehan** [comment]
Agreed, the final design looks fantastic, thanks @kristinashu!

**Comment by anmechung** [comment]
+1!  thanks @kristinashu
