### ISSUE TITLE
Collect email addresses before submission process is open

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/NSF-wireless-innovation-challenge#14]
Since we will likely have a multi-month gap between when the site launches and when we start accepting submissions, we thought it might be good to let users request to be notified via email.

This would just be a simple form to collect email addresses.

cc @simonwex - are we good to do this?

**Comment by ScottDowne** [comment]
I had a quick chat with @stephaniemcv around this, about if and how we can use Salesforce Marketing Cloud (SFMC) for this, using Journey Builder.

It looks like we can, and it looks like both the Internet Health Report already has a pattern for this, and it's modeled after Firefox subscription and interests.

I'm not 100% sure what all that means yet, but it what I do understand feels right.

**Comment by hannahkane** [comment]
^ sounds great, @ScottDowne. Thanks for investigating.

**Comment by hannahkane** [comment]
I think this is duped by #23, so closing
