### ISSUE TITLE
UI: Files for dev

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#16]
**Comps** 
https://redpen.io/p/cx1e480fd9bb50a788

**Copy doc** 
copy is not final
https://docs.google.com/a/mozilla.com/document/d/14kJKOpZmDEpI213alSW0Bmho1JbEYDNMsWLb2vFQ7jk/edit?usp=sharing

**Sketch file**
https://drive.google.com/open?id=0B2irLVDJivhLQklvYXV0YWYyYVE

**Images and icons**
https://drive.google.com/open?id=0B2irLVDJivhLUE1oLWlFVXpLRUU
- hero image
- NSF + Mozilla logos
- 6 challenge icons
- 4 location images
- icons for accordions
- footer icons from bootstrap

**Comment by kristinashu** [comment]
cc @mmmavis @gvn

**Comment by hannahkane** [comment]
Can we close this ticket?

**Comment by kristinashu** [comment]
I think so!
