### ISSUE TITLE
UI: nav bar

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#19]
Nav bar is sticky like on https://internethealthreport.org/v01/ but instead of linking to new pages, this one will just scroll the user further down the page.

Colors:
#F1F1F1 nav bar bg
#161616 selected text and hover state text
#7A7A7A unselected text

<img width="608" alt="screen shot 2017-01-23 at 2 18 04 pm" src="https://cloud.githubusercontent.com/assets/1068783/22225317/d171be72-e176-11e6-8da8-c8b7cc09197f.png">

**Comment by kristinashu** [comment]
Nav looks good, just wondering if it could 'animate' the scroll? So instead of jumping down the page, can it show the page scroll down/up? Not the nicest example but something like https://designshack.net/tutorialexamples/single-page-slider/

This is a nice-to-have enhancement.

**Comment by kristinashu** [comment]
Awesome, sounds like you've already done this!

**Comment by ScottDowne** [comment]
Fixing in https://github.com/mozilla/nsf-challenge/pull/11

**Comment by kristinashu** [comment]
Cool!

Right now clicking on "About" scroll the user to the top of the body text. I think it would be better if it linked to the very top of the page (like https://mozilla.github.io/nsf-challenge/). Is that doable? Make sense?

**Comment by ScottDowne** [comment]
Fixing the scroll to top for about in https://github.com/mozilla/nsf-challenge/pull/14

**Comment by ScottDowne** [comment]
Should be on staging now.
