### ISSUE TITLE
UI: Hover states

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#20]
## In line text: 
same as https://internethealthreport.org/v01/

regular <img width="668" alt="screen shot 2017-01-23 at 2 11 02 pm" src="https://cloud.githubusercontent.com/assets/1068783/22225067/dbf4f9d2-e175-11e6-947d-567bd1445054.png">

hover <img width="664" alt="screen shot 2017-01-23 at 2 11 05 pm" src="https://cloud.githubusercontent.com/assets/1068783/22225068/dbf6e292-e175-11e6-8e7a-064145757f06.png">

## Yellow buttons: 
same as https://internethealthreport.org/v01/open-innovation/

regular
<img width="311" alt="screen shot 2017-01-23 at 2 12 33 pm" src="https://cloud.githubusercontent.com/assets/1068783/22225197/62c2b396-e176-11e6-9e9b-fa35ae43bba2.png">

hover (slightly darker #FFE800)
<img width="326" alt="screen shot 2017-01-23 at 2 12 42 pm" src="https://cloud.githubusercontent.com/assets/1068783/22225195/60f5b25c-e176-11e6-8d8c-837a9c98301a.png">

## Nav bar: 
color changes on hover and selected/unselected
#F1F1F1 nav bar bg
#161616 selected text and hover state text
#7A7A7A unselected text

## Events: 
Hovering/clicking over photo or text will link to event form.
<img width="493" alt="screen shot 2017-01-23 at 2 29 44 pm" src="https://cloud.githubusercontent.com/assets/1068783/22225723/7e597c46-e178-11e6-8351-13da94fbbba2.png">

**Comment by ScottDowne** [comment]
The actual hover state colours on https://internethealthreport.org/v01/open-innovation/ are #FEE601

Non hover is colour is #FEEB34

**Comment by kristinashu** [comment]
Cool, go with that then.

**Comment by kristinashu** [comment]
This looks done, closing!
