### ISSUE TITLE
UI: Footer

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#21]
Mofo bootstrap component but with added section about NSF

Logo is in assets folder https://drive.google.com/open?id=0B2irLVDJivhLUE1oLWlFVXpLRUU

Links:
- Forum: https://forum.learning.mozilla.org/c/nsf-wins
- Legal: https://www.mozilla.org/en-US/about/legal/terms/mozilla/
- Privacy: https://www.mozilla.org/en-US/privacy/websites/
- Cookies: https://www.mozilla.org/en-US/privacy/websites/#cookies
- Challenge Rules: to be created on whatever domain we use for the challenge website (ideally, wirelesschallenge.mozilla.org/rules

**Comment by mmmavis** [comment]
@kristinashu we are missing the 🍪 icon still 😃

**Comment by kristinashu** [comment]
@mmmavis it's in the main footer ticket https://github.com/mozilla/mofo-bootstrap/issues/92#issuecomment-272573805

**Comment by kristinashu** [comment]
Footer looks good! Just needs the links above ^

**Comment by ScottDowne** [comment]
Fixing in https://github.com/mozilla/nsf-challenge/pull/12

**Comment by ScottDowne** [comment]
Footer links landed. (not sure if on staging yet, the way we do that is changing)
