### ISSUE TITLE
Form: email reminder

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#22]
@mehan when you have a URL for the form link, please add it here for dev to implement. 

<img width="598" alt="screen shot 2017-01-23 at 2 32 44 pm" src="https://cloud.githubusercontent.com/assets/1068783/22225836/e39d807a-e178-11e6-91db-399c6b6583bc.png">
<img width="598" alt="screen shot 2017-01-23 at 2 32 53 pm" src="https://cloud.githubusercontent.com/assets/1068783/22225837/e3a00a66-e178-11e6-9c26-462cc486a143.png">

**Comment by hannahkane** [comment]
@ScottDowne is thinking about the form in #14

**Comment by hannahkane** [comment]
@mehan - just a reminder that we're also waiting on this form. Let me know if I can help.

**Comment by hannahkane** [comment]
This turned out to be more complicated than expected, so we're going to remove the email sign-up.
