### ISSUE TITLE
QA for site

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/NSF-wireless-innovation-challenge#24]
@mehan @hannahkane @mmmavis We can put QA in here. Staging link is: <s>https://mozilla.github.io/nsf-challenge/</s> https://wirelesschallenge.mofostaging.net/
 - [x] Edit needed for copy in header image. "The NSF Wireless Innovation for a Networked Society (NSF WINS) Initiate is a series of challenges, powered by Mozilla, which seek projects that further innovation in a community wireless networks." [typo in word "Initiative" + last five words don't make sense. @mehan - should it read "that further innovation in community wireless networks"?]
 - [ ] Should "[Design Concept stage] and a [Working Prototype Stage]" in the "What we're looking for" section be linked to something?
 - [ ] Should both instances of "[judging criteria]" in the "Challenge" sections link to something?
 - [ ] Suggest clarifying that attendance at launch events is not required. cc @mehan 
 - [ ] Within the Details section: if I, for example, expand the "How to enter the challenge" section, and then scroll down and expand the "Timeline" section, I will be scrolled down to the _end_ of the section, which is confusing.
 - [ ] Should mozilla logo in header image link to mozilla.org?
 - [x] In Safari, mozilla logo in footer overlaps with other content.
![screen shot 2017-02-02 at 10 26 10 am](https://cloud.githubusercontent.com/assets/8389648/22562622/2b74fe4e-e932-11e6-8b7a-80069afb66cd.png)

**Comment by hannahkane** [comment]
Many of my QA comments so far (see above) are about content, rather than code/implementation. If that's going to be too annoying to sort through, perhaps we could have separate QA tickets for content vs implementation?

**Comment by ScottDowne** [comment]
@hannahkane nah, I'm fine with keeping it in here for content and implementation.

(I can help with copy changes too if things are slow for implementation changes ;))

**Comment by mehan** [comment]
To answer the question relating to the first checkbox--that's exactly right, it should read "that further innovation in community wireless networks". Good catch on the "initiative" typo as well.

**Comment by mehan** [comment]
I had originally had separate sections for the Design Prototype stage and the Working Prototype stage, so I had intended to have those link to anchors--I will remove those link placeholders when I revise that text.

**Comment by mehan** [comment]
If possible, it would be great to drop an anchor tag on each of the section headers--that way, [judging criteria] can link to the "What we're looking for" section, etc.

Scott's comment: Right now I have three anchors, which are the items in the sticky nav. Happy to add more that are linkable and not in the sticky nav. I'm just not 100% on which section headers you're referring to. Is "What we're looking for" the only header you want to be linked to, that's not currently linkable?

@ScottDowne Yep, I think that's the only additional one that would be needed. Thanks!

**Comment by mehan** [comment]
@ScottDowne I assume that the text that appears alongside these bullets will be populated from a markdown file?

![screen shot 2017-02-02 at feb 2 4 53 55 pm](https://cloud.githubusercontent.com/assets/1390212/22575091/5271101a-e968-11e6-904f-6abdf8a732ea.png)

If not, there is additional text that will need to be appended to each of those.

Scott's comment: Yup, the markdown for this should be in here: https://github.com/mozilla/nsf-challenge/tree/master/source/markdown/challenges

**Comment by mehan** [comment]
@ScottDowne The text in these tabs looks a bit off to me:

![screen shot 2017-02-02 at feb 2 4 55 27 pm](https://cloud.githubusercontent.com/assets/1390212/22575129/8f8ae87c-e968-11e6-9fb6-497287102757.png)

In Kristina's mock-ups, it was a lighter font weight and the text was centered--could we try something more like this?

![screen shot 2017-02-02 at feb 2 4 56 05 pm](https://cloud.githubusercontent.com/assets/1390212/22575144/a45934b6-e968-11e6-977a-e9559f1edf58.png)

Scott's comment: This is an interesting one. I don't see what you see. I say we file this as a separate issue. https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/25

**Comment by mehan** [comment]
@ScottDowne Assuming the headers for the accordions are hard-coded, they'll need to be updated. 

![screen shot 2017-02-02 at feb 2 4 59 02 pm](https://cloud.githubusercontent.com/assets/1390212/22575205/f1f847f2-e968-11e6-88a4-9a35b0564c4e.png)

The latest headers are as follows:

- Who can enter the challenges
- What to submit
- Timeline
- Judging and awards
- FAQ
- Getting Started

Scott's comment: I have this in the pipeline.
- [x] Update accordion headers

**Comment by mehan** [comment]
@ScottDowne The text in the "Find an event" and "Email sign up" buttons doesn't look properly vertically centered to me.

![screen shot 2017-02-02 at feb 2 5 01 29 pm](https://cloud.githubusercontent.com/assets/1390212/22575280/6432205e-e969-11e6-958a-954b7ed093f3.png)

Scott's comment: Should be fixed now.
- [x] info-box alignment issues

**Comment by mehan** [comment]
@ScottDowne On mobile, these two containers ("Learn more..." and "Submissions...") look like they might be different sizes?  

![img_3670](https://cloud.githubusercontent.com/assets/1390212/22575497/a9f2725a-e96a-11e6-83ce-63bff10dcfa1.PNG)

Scott's comment: Should be fixed now.
- [x] info-box alignment issues

**Comment by mehan** [comment]
![screen shot 2017-02-02 at feb 2 5 13 39 pm](https://cloud.githubusercontent.com/assets/1390212/22575551/15532328-e96b-11e6-8b7a-e07f4a03b67c.png)

@ScottDowne The language in this section should read as follows:

"NSF is an independent U.S. government agency responsible for promoting science and engineering through research programs and education projects. Visit us at nsf.gov."

Scott's comment: I have this in the pipeline.
- [x] Fix footer copy for nsf from pasted filler copy.

**Comment by ScottDowne** [comment]
@mehan I'm going to comment to your feedback, by editing your comments. Hope that's alright :)

**Comment by ScottDowne** [comment]
- [x] Cookies icon in the footer is not the right icon. I just used a placeholder. @kristinashu Is the cookie icon something I need to get from you?

**Comment by hannahkane** [comment]
I believe the cookie icon is linked here: https://github.com/mozilla/mofo-bootstrap/issues/92#issuecomment-272573805

**Comment by ScottDowne** [comment]
@hannahkane looks like the colour for that icon is off when compared to the others, the cookie icon is too dark. cc @kristinashu I think I need it to be white, that way I can darken it via opacity. Right now, I can darken it, but not lighten it, because I cannot set opacity to be 110%

**Comment by ScottDowne** [comment]
Either that, or there is some css magic happening in the footer I havn't run into yet. Looking.

**Comment by ScottDowne** [comment]
@kristinashu Ah, yes, the cookie icon is not solid white, but has opacity built in. This makes it impossible for me to make it solid white when on hover.

**Comment by ScottDowne** [comment]
@kristinashu nvm, I think I can just edit the svg myself, it's super simple.

**Comment by ScottDowne** [comment]
OK, did a bunch of fixes.

I think there is only one markdown related issue left, and that's some weirdness @hannahkane pointed out where the content in the expander, if long, doesn't scroll to the new content.

I'm thinking up a solution to this.

**Comment by hannahkane** [comment]
Something for @mehan - 
 - [x] remove "powered by Mozilla" clause from full sentence in header image since those words appear directly above

**Comment by hannahkane** [comment]
- [ ] NSF logo in footer should link to nsf.gov

**Comment by hannahkane** [comment]
Closing this ticket since all non-content issues have been addressed except for the accordion scrolling thing, which I've dropped into a new issue (#35).

@mehan - if the content issues here are useful for you to reference, feel free to re-open.
