### ISSUE TITLE
UI: add button arrow

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#26]
Please add the button arrow. It should be the same arrow seen on https://internethealthreport.org/v01/web-literacy/
<img width="160" alt="screen shot 2017-02-06 at 10 09 46 am" src="https://cloud.githubusercontent.com/assets/1068783/22659963/7fa8ef82-ec54-11e6-94e4-7eb523accd76.png">

But on the button like this:
<img width="212" alt="screen shot 2017-02-06 at 10 09 57 am" src="https://cloud.githubusercontent.com/assets/1068783/22659964/7faac1fe-ec54-11e6-893c-53997912bf70.png">

**Comment by ScottDowne** [comment]
Fixing in https://github.com/mozilla/nsf-challenge/pull/27
