### ISSUE TITLE
Add fav icon

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#27]
Icon mozilla's new fav icon: assets are in the folder https://drive.google.com/open?id=0B2irLVDJivhLOVpHTThnaDgtQXc

**Comment by ScottDowne** [comment]
Fixing in https://github.com/mozilla/nsf-challenge/pull/22

**Comment by ScottDowne** [comment]
Fixed and on staging
