### ISSUE TITLE
Event photo styling on mobile

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#31]
Event grid should be 2 up on mobile instead of 1 up (so reduce scroll length).

Example for the comp on the left and staging on the right.

<img width="671" alt="screen shot 2017-02-06 at 10 35 08 am" src="https://cloud.githubusercontent.com/assets/1068783/22660962/4a3798e0-ec58-11e6-87c2-4913fa14db1d.png">

**Comment by ScottDowne** [comment]
Fixes in here: https://github.com/mozilla/nsf-challenge/pull/13
