### ISSUE TITLE
Add link on Rules and Regulation page back to home page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#32]
Yellow title text on Rules and Regulation page (https://mozilla.github.io/nsf-challenge/rules-and-regulations/) should link to home page (https://mozilla.github.io/nsf-challenge/).

<img width="1268" alt="screen shot 2017-02-06 at 10 40 36 am" src="https://cloud.githubusercontent.com/assets/1068783/22661065/c9274f24-ec58-11e6-9acd-c071cc6ce8a5.png">

**Comment by ScottDowne** [comment]
Is there a hover state?

**Comment by ScottDowne** [comment]
Fixing in https://github.com/mozilla/nsf-challenge/pull/19

**Comment by kristinashu** [comment]
Color change could be the same as the yellow CTA buttons (the slightly darker shade of yellow).

**Comment by ScottDowne** [comment]
Should be on staging now.
