### ISSUE TITLE
Add anchor link to "Find an Event" buttons

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#33]
Both buttons should link to the Launch Event section (same functionality as if I clicked on "Events" in the nav). 

<img width="176" alt="screen shot 2017-02-06 at 10 47 33 am" src="https://cloud.githubusercontent.com/assets/1068783/22661339/dde1f918-ec59-11e6-9978-c404c267d3ea.png">
<img width="338" alt="screen shot 2017-02-06 at 10 47 38 am" src="https://cloud.githubusercontent.com/assets/1068783/22661338/dde1b7f0-ec59-11e6-9a49-ad160e8c2b77.png">

**Comment by ScottDowne** [comment]
Fixing in https://github.com/mozilla/nsf-challenge/pull/26
