### ISSUE TITLE
URL should update as user scrolls down the page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#34]
Sorry, I didn't list this as a requirement but I think the URL should update as the user scrolls through each main section (about, events, details)

Example on staging (the URL should be https://mozilla.github.io/nsf-challenge/#details):

<img width="1329" alt="screen shot 2017-02-06 at 10 44 51 am" src="https://cloud.githubusercontent.com/assets/1068783/22661618/dd0165d2-ec5a-11e6-9085-721e4b1e6479.png">

**Comment by ScottDowne** [comment]
Fixing in https://github.com/mozilla/nsf-challenge/pull/20

**Comment by ScottDowne** [comment]
This landed in mozilla/nsf-challenge#20
