### ISSUE TITLE
Determine proper behavior for expanding accordions and scrolling

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/NSF-wireless-innovation-challenge#35]
Within the Details section: if I, for example, expand the "How to enter the challenge" section, and then scroll down and expand the "Timeline" section, I will be scrolled down to the end of the section, which is confusing.

**Comment by hannahkane** [comment]
@ScottDowne - do we need this ticket, or is this covered in #17?

**Comment by ScottDowne** [comment]
Let's keep them both open. I have a pull request that is fixing everything in #17 without fixing this bug.

**Comment by hannahkane** [comment]
Fixed on staging.
