### ISSUE TITLE
Add cc license 

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/NSF-wireless-innovation-challenge#36]
Legal requests the addition of this sentence to the site. @kristinashu - thoughts on how to best integrate this into the footer?

"This website is licensed under a [Creative Commons license](https://creativecommons.org/licenses/by-sa/3.0/deed.en), excluding portions of the content attributed to third parties."

**Comment by kristinashu** [comment]
I guess stick it at the bottom...

<img width="1059" alt="screen shot 2017-02-17 at 3 37 10 pm" src="https://cloud.githubusercontent.com/assets/1068783/23087286/c9687814-f527-11e6-8aa8-9421aae7f127.png">

**Comment by hannahkane** [comment]
Closing in lieu of https://github.com/mozilla/nsf-challenge/issues/59
