### ISSUE TITLE
Determine design direction

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#4]
We need to decide if we will use MoCo's new branding or if we will stick to MoFo's Unified Design style. This will determine color, font, photography, icon style... Most likely it will follow MoCo's new branding, if so, we need to find out what that is.

**Comment by hannahkane** [comment]
cc @xmatthewx to provide guidance here

**Comment by kristinashu** [comment]
We will be using MoCo's new brand since it's what MLN will be using. MoCo will be sharing the new direction this Wednesday. I'll be able to add/update color, font and some styling then.

**Comment by kristinashu** [comment]
Closing this ticket and opened one for designing the site https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/13
