### ISSUE TITLE
Research Fluxx

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#5]
We plan to use [Fluxx](https://www.fluxx.io/) for form application submissions. 

@mehan when you can, please confirm this is what we will be using. Also, is the intention that we will simply link to the Fluxx form from our site (or will it require integration into our site)? 

cc @mmmavis

**Comment by hannahkane** [comment]
Also want to confirm that Fluxx has been approved as a vendor. Has it passed security review?

**Comment by mehan** [comment]
@anmechung may be able to provide some insight regarding Fluxx's status re: approved vendor, security, etc.

At the moment, our intent is to use Fluxx for the application form but that's contingent on them being able to build out forms that suit our needs. We're working to schedule a call with them for next week, so I should hopefully have an answer for them by that time. I'll also confirm that they can expose a web form that we can simply link to.

**Comment by anmechung** [comment]
@hannahkane Fluxx has been approved as vendor, passed security review, and contract signed.

**Comment by hannahkane** [comment]
Closing this; and will open tickets later to implement the Fluxx-handled submission process
