### ISSUE TITLE
Discourse Forum

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#6]
Sounds like we will use [Discourse](http://www.discourse.org/) for the discussion forum. 

@mehan when you can, please confirm if we will in fact use discourse. Also, is the intention that we would simply link to the forum from our website?

cc @mmmavis

**Comment by anmechung** [comment]
may want to check with @KGorr about using discourse as she's been working on consolidating and having less specific projects and more general topic areas.

**Comment by mehan** [comment]
Lainie suggested that we might be able to add a sub-forum for the challenges to the MLN Discourse. I will confirm that with her and circle back. And yes, @kristinashu, our intent was that the site would simply link to that sub-forum, unless you guys recommend a deeper integration.

**Comment by kristinashu** [comment]
Sounds great, thanks @mehan!

**Comment by mehan** [comment]
The Discourse sub-forum is all set! Here's the link:

https://forum.learning.mozilla.org/c/nsf-wins

**Comment by kristinashu** [comment]
Excellent!
