### ISSUE TITLE
Gather images

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#7]
Need to source images we could use for the site.

**Comment by anmechung** [comment]
@mehan - also may want to check with NSF for approved images?

**Comment by mehan** [comment]
@anmechung Yep, I will reach out and see--I think we'll at least want approved assets like the NSF logo, etc.

**Comment by mehan** [comment]
Actually, it looks like all of those sort of assets [are here](https://www.nsf.gov/policies/logos.jsp).

**Comment by kristinashu** [comment]
Here are a few possible background images for the top of the page:

![01](https://cloud.githubusercontent.com/assets/1068783/21911411/8d622392-d8d5-11e6-9486-c85721f1058e.jpg)
![02](https://cloud.githubusercontent.com/assets/1068783/21911412/8d6279d2-d8d5-11e6-8ce6-fc1cf6036da0.jpg)
![03](https://cloud.githubusercontent.com/assets/1068783/21911413/8d62b1ea-d8d5-11e6-9613-8f252934430f.jpg)
![05](https://cloud.githubusercontent.com/assets/1068783/21911415/8d640748-d8d5-11e6-841f-4c5c457afe4c.jpg)

cc @hannahkane

**Comment by mehan** [comment]
That first one feels the most "internetty" to me, if that makes sense? I like that direction.

**Comment by hannahkane** [comment]
Agree with @mehan's point. I also like the third one, aesthetically.

I know we're just talking about the bg image here, but wanted to suggest that we don't break "Networked" and "Society," if we can avoid it.

**Comment by kristinashu** [comment]
Great! We can use image 1 at the top of the page and then image 3 towards the bottom of the page (background for the call-to-action section).

I'll adjust the colors a little to brighten it up once we see the final moco rebrand colors this Wednesday.
