### ISSUE TITLE
DUE JAN 11: Sketch of content

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/NSF-wireless-innovation-challenge#8]
The content doesn't need to be final, or even near final, but we do need a sense of how much content there will be and what the calls-to-action will be

**Comment by mehan** [comment]
I just went ahead and tried to add some more context to each of the wiki pages to this effect. Let me know if that's helpful and if you guys need additional information at this stage.

One thing that occurred to me while I was sketching this out: we will likely want separate pages for things like the official challenge rules, legal information and privacy policy. I noticed that the Equal Rating Challenge site has stand-alone pages for each of those, which are linked to in the footer--we might want to consider an approach like that.

![screen shot 2017-01-09 at jan 9 3 37 48 pm](https://cloud.githubusercontent.com/assets/1390212/21788091/a6405eca-d681-11e6-8ee7-b18f57adc4b4.png)

Let me know if I should add additional pages to the wiki for those pages.

**Comment by hannahkane** [comment]
Thanks, @mehan.

Are we writing up Terms and a Privacy Policy specific to the challenges? If so, then yes, we should build those pages and link to them from the footer (the alternative would be to link to our standard Terms and Privacy docs).

**Comment by mehan** [comment]
@hannahkane I will check with Abigail and report back in this thread. My assumption is that we can use the standard privacy policy, though we will need a set of "challenge rules" that is unique to these challenges.

**Comment by hannahkane** [comment]
OK, let's move this conversation to #11.

Closing this ticket since we have an initial sketch of content.
